### ISSUE TITLE
Can't build master

### ISSUE THREAD

**Issue by nelsongraca** [jboss-fuse/fabric8#695]
I was trying to build the code currently on master but I'm getting the following error:
`[ERROR] Failed to execute goal on project shared-commands: Could not resolve dependencies for project org.jboss.fuse:shared-commands:bundle:6.3.0.redhat-SNAPSHOT: Failed to collect dependencies at io.fabric8:fabric-utils:jar:1.2.0.redhat-630107 -> io.fabric8:common-util:jar:1.2.0.redhat-630107 -> org.slf4j:slf4j-api:jar:1.7.7.redhat-2: Failed to read artifact descriptor for org.slf4j:slf4j-api:jar:1.7.7.redhat-2: Could not transfer artifact org.slf4j:slf4j-api:pom:1.7.7.redhat-2 from/to brewroot (http://download.eng.bos.redhat.com/brewroot/repos/jb-fuse-6.2-build/latest/maven): download.eng.bos.redhat.com: Unknown host download.eng.bos.redhat.com -> [Help 1]`

**Comment by tadayosi** [comment]
Sorry but it may not build outside of Red Hat intranet.

**Comment by nelsongraca** [comment]
Sure much for open source...

**Comment by tadayosi** [comment]
@nelsongraca This is a product repo. Please look at https://github.com/fabric8io/fabric8 for the community project.
